export const TaskList = [
  'Recepción de traspaso de CEDIS',
  'Revisión-acomodo de traspaso de proveedor',
  'Conteo de inventarios',
  'Reconteo de inventarios',
  'Conteo inventario mesa de ayuda',
  'Reconteo inventario mesa de ayuda',
  'Tarea especial de inventarios para sucursal',
  'Surtir pedido cliente',
  'Revisar pedido',
  'Empacar pedido',
  'Revisión-acomodo de traspaso de CEDIS',
  'Revisión de garantía de mostrador',
  'Revisión de devolución de mostrador',
  'Recepción de traspaso de sucursal',
  'Revisión-acomodo de traspaso de sucursal',
  'Revisión de garantías de clientes de agentes',
  'Revisión de devoluciones de clientes de agentes',
  'Tarea automática especial de inventarios',
  'Conteo gerentes regionales',
  'Conteo semanal admon',
  'Reconteo de tareas automaticas especiales',
  'Conteo inventario Retail',
  'Reconteo inventario Retail',
  'Conteo especial Retail',
  'Reconteo especial Retail',
  'Conteo automatico especial Retail',
  'Reconteo automatico especial Retail',
  'Conteo de inventarios de consigna',
  'Conteo nuevo gerentes regional',
  'Surtido de traspasos de balanceo de inventario',
  'Revisar traspaso de balanceo de inventario',
  'Empacar traspaso de balanceo de inventario',
  'Conteo inventario gerente regional',
  'Reconteo inventario gerente regional',
] as const;